INSERT INTO games (id, title, platform, image, genres, description, price, year, developer, publisher, req_min, req_rec, trailer, link, is_parted) VALUES
(
    1,
    'Red Dead Redemption 2',
    'pc',
    'source/game1.jpg',
    '["Action","      Adventure"]'::jsonb,
    'Petualangan epik dari Rockstar Games yang membawa pemain ke Amerika pada akhir abad ke-19. Kamu berperan sebagai Arthur Morgan, seorang anggota geng Van der Linde, yang hidup dalam dunia penuh kekerasan, moral abu-abu, dan pilihan sulit. Game ini menghadirkan dunia terbuka terbesar dan paling detail yang pernah dibuat Rockstar, dengan hutan, kota, pegunungan, hingga rawa yang bisa dijelajahi bebas. Cerita berfokus pada loyalitas, kehormatan, dan pengkhianatan di tengah keruntuhan era koboi. Selain misi utama, pemain bisa berburu, memancing, berdagang, dan berinteraksi dengan ratusan karakter unik.rnrnOriginal From: https://www.ovagames.com/964963-red-dead-redemption-2-multi13-elamigos.html (ovagames.com)rnrnPassword: www.ovagames.com',
    'Rp 499.000 (Free Download Available)',
    2018,
    'Rockstar Games',
    'Rockstar Games',
    '{"os":"Windows 10 (64-bit)","processor":"ntel Core i5-2500K / AMD FX-6300","memory":"8 GB RAM","graphics":"Nvidia GTX 770 2GB / AMD R9 280 3GB","storage":"150 GB available space"}'::jsonb,
    '{"os":"Windows 10 (64-bit)","processor":"Intel Core i7-4770K / AMD Ryzen 5 1500X","memory":"12 GB RAM","graphics":"Nvidia GTX 1060 6GB / AMD RX 480 4GB","storage":"150 GB available space"}'::jsonb,
    'https://www.youtube.com/embed/eaW0tYpxyp0',
    'https://www.filecrypt.cc/Container/8711E7056F.html',
    0
  ),
(
    2,
    'Hollow Knight: Silksong',
    'pc',
    'source/game2.jpg',
    '["Action","  Platformer"]'::jsonb,
    'Sekuel dari Hollow Knight yang sangat dinanti. Kali ini kamu mengendalikan Hornet, putri penjaga kerajaan Hallownest. Tertangkap dan dibawa ke sebuah kerajaan asing yang misterius, Hornet harus melawan musuh-musuh mematikan sambil mengungkap rahasia dunia baru ini. Gameplay berupa platformer metroidvania dengan ratusan area baru, musuh beragam, bos epik, dan sistem pertarungan cepat berbasis jarum khas Hornet. Selain eksplorasi bawah tanah, pemain akan menemukan kota baru, karakter NPC dengan cerita unik, serta tantangan sampingan.rnrnOriginal From: https://steamrip.com/hollow-knight-silksong-free-download/ (SteamRIP)',
    'Rp 299.000 (Free Download Available)',
    2025,
    'Team Cherry',
    'Team Cherry',
    '{"os":"Windows 10","processor":"Intel Core i3","memory":"4 GB RAM","graphics":"GeForce GTX 650","storage":"20 GB available space"}'::jsonb,
    '{"os":"Windows 10","processor":"Intel Core i5","memory":"8 GB RAM","graphics":"GeForce GTX 960","storage":"20 GB available space"}'::jsonb,
    'https://www.youtube.com/embed/6XGeJwsUP9c',
    'https://gofile.io/d/vu9S1a',
    0
  ),
(
    3,
    'Need For Speed Heat',
    'pc',
    'source/game3.png',
    '["Racing","    Action"]'::jsonb,
    'Game balap dunia terbuka dari EA yang membawa pemain ke Palm City, kota fiksi terinspirasi Miami. Siang hari, kamu bisa ikut balapan resmi untuk mendapatkan uang. Malam hari, semuanya berubah menjadi balapan liar penuh risiko di jalanan kota. Polisi menjadi ancaman besar pada malam hari, mengejar tanpa henti. Sistem â€œRisk vs Rewardâ€ membuat pemain harus memilih apakah akan pulang untuk menyimpan reputasi atau terus balapan dengan resiko tertangkap. Game ini menggabungkan kustomisasi mobil mendalam, musik energik, dan atmosfer jalanan yang intens.rnrnOriginal From: https://www.yasir252.com/game/download-need-for-speed-heat-full-version-pc-gratis/ (yasir252.com)rnrnPassword: www.yasir252.com',
    'Rp 399.000 (Free Download Available)',
    2019,
    'Ghost Games',
    'Electronic Arts',
    '{"os":"Windows 10 (64-bit)","processor":"Intel Core i5-3570 / AMD FX-6350","memory":"8 GB RAM","graphics":"NVIDIA GeForce GTX 760 / AMD Radeon 7970","storage":"50 GB available space"}'::jsonb,
    '{"os":"Windows 10 (64-bit)","processor":"Intel Core i7-4790 / AMD Ryzen 3 1300X","memory":"16 GB RAM","graphics":"NVIDIA GeForce GTX 1060 / AMD Radeon RX 480","storage":"50 GB available space"}'::jsonb,
    'https://www.youtube.com/embed/n1xdf-YM5k0',
    'https://www.mediafire.com/folder/6geijukbyyabk/NFSH',
    0
  ),
(
    4,
    'Resident Evil 4 (USA)',
    'ps2',
    'source/ResidentEvil4.jpg',
    '["Survival Horror","   Action","   Third-Person Shooter","   Adventure"]'::jsonb,
    '*Resident Evil 4 (2005)* adalah game survival horror ikonik dari Capcom yang mengikuti perjalanan Leon S. Kennedy dalam menyelamatkan putri Presiden dari kultus misterius di pedesaan Spanyol. Menghadirkan perpaduan aksi intens dan horor menegangkan, game ini memperkenalkan sistem kamera *over-the-shoulder* yang revolusioner, musuh Ganado yang agresif, serta berbagai lokasi mencekam mulai dari desa terpencil hingga kastil berbahaya. Dengan gameplay cepat, senjata yang dapat ditingkatkan, dan karakter-karakter memorable seperti Ada Wong, game ini diakui sebagai salah satu judul terbaik sepanjang masa dalam genre aksi-horor.rnrnOriginal From: https://cdromance.org/ps2-iso/resident-evil-4-usa-2/',
    'Free Download Available',
    2005,
    'Capcom Production Studio 4',
    'Capcom',
    '{"os":"Windows XP / Windows Vista","processor":"Intel Pentium 4 1.4 GHz","memory":"256 MB RAM","graphics":"DirectX 9.0c compatible, 128 MB VRAM (GeForce 6600 / ATI Radeon 9000 series)","storage":"7 GB space tersedia"}'::jsonb,
    '{"os":"Windows XP / Vista / Windows 7","processor":"Intel Pentium 4 2.4 GHz atau setara","memory":"1 GB RAM","graphics":"DirectX 9.0c compatible, 256 MB VRAM (GeForce 8000 series / Radeon X series)","storage":"7 GB space tersedia"}'::jsonb,
    'https://www.youtube.com/embed/1KTghW30ZuY?si=-FPPbh0DrAZ2K5P_',
    'https://dl9.cdromance.org/download.php?file=Resident%20Evil%204%20%28USA%29.7z&id=81103&platform=ps2-iso&key=9163263556',
    0
  ),
(
    5,
    'It Takes Two',
    'pc',
    'source/download.jpg',
    '["Action"," Adventure"," Co-op"," Puzzle"," Platformer"]'::jsonb,
    'Game petualangan co-op yang menceritakan pasangan suami istri, Cody dan May, yang berubah menjadi boneka kecil dan harus bekerja sama untuk kembali ke tubuh mereka. Game ini menekankan kerja sama dua pemain dengan berbagai mekanik gameplay unik di setiap level.rnrnOriginal Link : https://www.elamigosweb.com/game/it-takes-two (ElAmigos)',
    'Free',
    2021,
    'Hazelight Studios',
    'Electronic Arts',
    '{"os":"Windows 8.1 64-bit / Windows 10 64-bit","processor":"Intel Core i3-2100T / AMD FX 6100","memory":"8 GB","graphics":"NVIDIA GeForce GTX 660 / AMD Radeon R7 260x","storage":"50 GB"}'::jsonb,
    '{"os":"Windows 10 64-bit","processor":"Intel Core i5-3570K / AMD Ryzen 3 1300X","memory":"16 GB","graphics":"NVIDIA GeForce GTX 980 / AMD Radeon RX 590","storage":"50 GB"}'::jsonb,
    'https://www.youtube.com/embed/GAWHzGNcTEw',
    '#',
    1
  ),
(
    6,
    'Detroit: Become Human',
    'pc',
    'source/image.jpg',
    '["Adventure","  Interactive Story","  Sci-Fi","  Story Rich"," Choices Matter"]'::jsonb,
    'Detroit: Become Human adalah game cerita interaktif yang berlatar di masa depan, di mana android hidup berdampingan dengan manusia. Pemain mengendalikan tiga karakter android berbeda yaitu Kara, Connor, dan Markus yang masing-masing memiliki jalan cerita unik. Setiap pilihan yang diambil akan memengaruhi alur cerita dan menentukan berbagai kemungkinan ending.rnrnOriginal Link : https://www.ovagames.com/80456-detroit-become-human-codex.html (OvaGames)',
    'Free Download Available',
    2018,
    'Quantic Dream',
    'Sony Interactive Entertainment (PS4), Quantic Dream (PC)',
    '{"os":"Windows 10 (64-bit)","processor":"Intel Core i5-2300 / AMD FX-8350","memory":"8 GB","graphics":"NVIDIA GeForce GTX 780 / AMD Radeon HD 7950","storage":"55 GB"}'::jsonb,
    '{"os":"Windows 10 / 11 (64-bit)","processor":"Intel Core i5-6600 / AMD Ryzen 3 1300X","memory":"12 GB","graphics":"NVIDIA GeForce GTX 1060 / AMD Radeon RX 580","storage":"55 GB"}'::jsonb,
    'https://www.youtube.com/embed/8a-EObAhYrg?si=Lrtw90BHqhpplkkH',
    'https://www.filecrypt.cc/Container/46E60B05E8.html',
    0
  ),
(
    7,
    'Resident Evil 4 Remake',
    'pc',
    'source/Resident-Evil-4-Remake-Wallpaper.jpg',
    '["Action","  Survival Horror","  Third-Person Shooter","  Adventure"]'::jsonb,
    'Resident Evil 4 Remake adalah versi remake dari game klasik tahun 2005 dengan grafis modern dan gameplay yang diperbarui. Pemain mengikuti agen Leon S. Kennedy dalam misi menyelamatkan putri presiden yang diculik di sebuah desa misterius di Eropa. Game ini menghadirkan pengalaman survival horror yang lebih intens dengan visual realistis dan mekanik gameplay yang lebih halus.',
    'Free Download Available',
    2023,
    'Capcom',
    'Capcom',
    '{"os":"Windows 10 64-bit","processor":"Intel Core i5-7500 / AMD Ryzen 3 1200","memory":"8 GB","graphics":"NVIDIA GeForce GTX 1050 Ti / AMD Radeon RX 560","storage":"60 GB"}'::jsonb,
    '{"os":"Windows 10 / 11 64-bit","processor":"Intel Core i7-8700 / AMD Ryzen 5 3600","memory":"16 GB","graphics":"NVIDIA GeForce GTX 1070 / AMD Radeon RX 5700","storage":"60 GB"}'::jsonb,
    'https://www.youtube.com/embed/Id2EaldBaWw',
    'https://drive.google.com/file/d/10nXsUJliPrse65Riq1ipF-A6qlG1M3IS/view?usp=drive_link',
    0
  ),
(
    8,
    'Tekken 7 Ultimate Edition',
    'pc',
    'source/TEKKEN7-men.jpg',
    '["Fighting","    Action"]'::jsonb,
    'Tekken 7 merupakan seri ketujuh dari franchise game fighting legendaris yang menggunakan Unreal Engine 4. Game ini menutup saga perseteruan keluarga Mishima yang telah berlangsung lama. Dengan sistem baru seperti Rage Arts, Power Crushes, dan Rage Drives, game ini menawarkan mekanisme pertarungan yang intens baik untuk pemula maupun pemain profesional. Terdapat lebih dari 30 karakter, termasuk tamu spesial seperti Akuma dari Street Fighter dan Noctis dari Final Fantasy XV.rnrnPass: www.ovagames.comrnrnOriginal: https://www.ovagames.com/892255-tekken-7-ultimate-edition-multi11-elamigos.html (Ovagames)',
    'Tersedia',
    2017,
    'Bandai Namco Studios',
    'Bandai Namco Entertainment',
    '{"os":"Windows 7/8/10 (64-bit OS required)","processor":"tel Core i3-4160 @ 3.60GHz or equivalent","memory":"6 GB RAM","graphics":"NVIDIA GeForce GTX 660 2GB, GTX 750Ti 2GB, or equivalent","storage":"60 GB available space"}'::jsonb,
    '{"os":"Windows 7/8/10 (64-bit OS required)","processor":"Intel Core i5-4690 3.5 GHz or equivalent","memory":"8 GB RAM","graphics":"NVIDIA GeForce GTX 1060 equivalent or higher","storage":"0 GB available space"}'::jsonb,
    'https://www.youtube.com/embed/kKLCwDg2JLA?si=P1LEfTc5_SVDfKzO',
    'https://www.filecrypt.cc/Container/0A29CBACFA.html',
    0
  ),
(
    9,
    'Assassinâ€™s Creed Odyssey Gold Edition',
    'pc',
    'source/ACOD_Standard_Capsule-1920x1080-a3ae1ed02ce5e7e9d13d8eb4558d07a959ce24ee.jpg',
    '["Action","      Adventure","      RPG","      Open World"]'::jsonb,
    'Assassin''s Creed Odyssey membawa pemain ke masa Yunani Kuno di tengah Perang Peloponnesos. Kamu bisa memilih bermain sebagai Alexios atau Kassandra, seorang tentara bayaran (Misthios) yang mencari kebenaran tentang keluarganya. Game ini memperkenalkan elemen RPG yang kental seperti pilihan dialog yang mempengaruhi cerita, kustomisasi perlengkapan yang mendalam, dan pertempuran laut yang epik. Visual dunianya sangat memukau, mulai dari patung-patung dewa yang raksasa hingga laut Aegea yang jernih.rnrnOriginal: https://www.ovagames.com/536665-assassins-creed-odyssey-gold-edition-multi15-elamigos.html (Ovagames)rnrnPass: www.ovagames.com',
    'Free Download Available',
    2018,
    'Ubisoft Quebec',
    'Ubisoft',
    '{"os":"Windows 7 SP1, Windows 8.1, Windows 10 (64-bit versions only)","processor":"AMD FX 6300 @ 3.8 GHz, Ryzen 3 - 1200, Intel Core i5 2400 @ 3.1 GHz","memory":"8 GB RAM","graphics":"AMD Radeon R9 285, NVIDIA GeForce GTX 660 (2GB VRAM with Shader Model 5.0)","storage":"46 GB available space"}'::jsonb,
    '{"os":"Windows 10 (64-bit versions only)","processor":"AMD FX-8350 @ 4.0 GHz, Ryzen 5 - 1400, Intel Core i7-3770 @ 3.5 GHz","memory":"8 GB RAM","graphics":"AMD Radeon R9 290, NVIDIA GeForce GTX 970 (4GB VRAM with Shader Model 5.0)","storage":"46 GB available space"}'::jsonb,
    'https://www.youtube.com/embed/6F8L3d_OIE0?si=QsO5sa6MWX57AofL',
    'https://www.filecrypt.cc/Container/1C084D9FB4.html',
    0
  ),
(
    10,
    'Watch Dogs Complete Edition',
    'pc',
    'source/watch-dogs-pc-game-ubisoft-connect-europe-cover.jpg',
    '["Action","   Adventure","   Open World","   Stealth"]'::jsonb,
    'Di Watch Dogs, kamu berperan sebagai Aiden Pearce, seorang *hacker* brilian sekaligus mantan kriminal yang mencari keadilan setelah tragedi keluarganya. Berlatar di Chicago yang dikendalikan oleh sistem operasi pusat bernama ctOS, kamu bisa meretas hampir semua hal: lampu lalu lintas, kamera pengawas, jembatan, hingga data pribadi penduduk. Game ini memadukan aksi tembak-menembak yang intens dengan elemen stealth dan kemahiran teknologi untuk memanipulasi lingkungan kota sebagai senjata utamamu.',
    'Free Download Available',
    2014,
    'Ubisoft Montreal',
    'Ubisoft',
    '{"os":"Windows Vista (SP2), Windows 7 (SP1) or Windows 8 (64 bit only)","processor":"Intel Core 2 Quad Q8400 @ 2.66Ghz or AMD Phenom II X4 940 @ 3.0Ghz","memory":"6 GB RAM","graphics":"NVIDIA GeForce GTX 460 or AMD Radeon HD 5770 (1GB VRAM dengan DirectX 11)","storage":"25 GB available space"}'::jsonb,
    '{"os":"Windows 7 (SP1) or Windows 8 (64 bit only)","processor":"Intel Core i7-3770 @ 3.5 GHz or AMD FX-8350 @ 4.0 GHz","memory":"8 GB RAM","graphics":"NVIDIA GeForce GTX 560 ti or AMD Radeon HD 7850 (2GB VRAM atau lebih)","storage":"25 GB available space"}'::jsonb,
    'https://www.youtube.com/embed/PFko4Kut39s?si=_YeHmgRD40Yz-Cbg',
    'https://drive.google.com/file/d/1DjquPoZA9mPuO7lq3QV_E5sHFof-0qLD/view?usp=drive_link',
    0
  );