-- Buat tabel reports
CREATE TABLE reports (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  game_id BIGINT,
  game_title TEXT,
  status TEXT DEFAULT 'pending',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Izinkan publik untuk melakukan INSERT (laporan)
ALTER TABLE reports ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public insert to reports"
ON reports FOR INSERT
TO public
WITH CHECK (true);

-- Hanya Admin yang bisa membaca/menghapus (secara default Supabase RLS akan memblokir select tanpa policy, yang mana aman)
-- Tapi kalau admin butuh lihat dari dashboard supabase, role 'postgres' dan 'service_role' tetap bisa lewat.
