-- Buat tabel games
CREATE TABLE games (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title TEXT,
  platform TEXT,
  image TEXT,
  genres JSONB,
  description TEXT,
  price TEXT,
  year INTEGER,
  developer TEXT,
  publisher TEXT,
  req_min JSONB,
  req_rec JSONB,
  trailer TEXT,
  link TEXT,
  is_parted SMALLINT DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Atur kebijakan keamanan (RLS) agar semua orang bisa membaca (read-only) secara publik
ALTER TABLE games ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access" 
ON games FOR SELECT 
TO public 
USING (true);
